from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('autoridades/', views.autoridades, name='autoridades'),
    path('organigrama/', views.organigrama, name='organigrama'),
    path('planificacion-estrategica/', views.planificacion_estrategica, name='planificacion_estrategica'),
    path('sedes-campus/', views.sedes_campus, name='sedes_campus'),
    path('carreras/', views.carreras, name='carreras'),
    path('carreras/<slug:career_slug>/', views.detalle_carreras, name='detalle_carreras'),
    path('validacion-experiencia/', views.validacion_experiencia, name='validacion_experiencia'),
    path('registro-carreras/', views.registro_carreras, name='registro_carreras'),
    path('biblioteca/', views.biblioteca, name='biblioteca'),
    path('portal-empleo/', views.portal_empleo, name='portal_empleo'),
    path('asociacion-graduados/', views.asociacion_graduados, name='asociacion_graduados'),
    path('soporte-tecnico/', views.soporte_tecnico, name='soporte_tecnico'),
    path('unidad-titulacion/', views.unidad_titulacion, name='unidad_titulacion'),
    path('cec-tecno/', views.cec_tecno, name='cec_tecno'),
    path('bienestar/', views.bienestar, name='bienestar'),
    path('vinculacion/', views.vinculacion, name='vinculacion'),
    path('investigacion/', views.investigacion, name='investigacion'),
    path('tecno-informativo/', views.tecno_informativo, name='tecno_informativo'),
    path('proceso-admision/', views.proceso_admision, name='proceso_admision'),
    path('becas-incentivos/', views.becas_incentivos, name='becas_incentivos'),
    path('inscripcion/', views.inscripcion, name='inscripcion'),
    path('multimedia/', views.multimedia, name='multimedia'),
    path('multimedia/subir/', views.upload_media, name='upload_media'),
    path('contacto/', views.contacto, name='contacto'),
    path('presentacion-institucional/', views.presentacion_institucional, name='presentacion_institucional'),
    path('aseguramiento-calidad/', views.aseguramiento_calidad, name='aseguramiento_calidad'),
    path('gaceta-institucional/', views.gaceta_institucional, name='gaceta_institucional'),
    path('transparencia/', views.transparencia, name='transparencia'),
    path('aviso-legal/', views.aviso_legal, name='aviso_legal'),
    path('politica-privacidad/', views.politica_privacidad, name='politica_privacidad'),
]
